import { type Event, type Guest } from "./supabase"

export const DEMO_EVENT: Event = {
  id: "demo-event-sofia-y-alejandro",
  slug: "demo",
  title: "Sofía & Alejandro",
  event_type: "boda",
  event_date: "2026-11-14T23:00:00+00:00",
  venue_name: "Hacienda Los Arcángeles",
  venue_address: "Av. del Bosque 320, San Pedro Garza García, N.L.",
  venue_maps_url: "https://maps.google.com/?q=San+Pedro+Garza+Garcia",
  host_name: "Sofía Morales & Alejandro Cantú",
  host_phone: "+52 81 8083 6435",
  host_email: "contacto@invitacionesdigitalesmty.com.mx",
  plan: "premium",
  has_whatsapp_addon: true,
  whatsapp_tier: "premium",
  has_seating_addon: false,
  created_at: "2026-08-15T00:00:00.000000+00:00",
}

export const DEMO_GUESTS: Guest[] = [
  {
    id: "demo-guest-1",
    event_id: "demo-event-sofia-y-alejandro",
    token: "familia_gonzalez_morales_4812",
    name: "Familia González Morales (4 personas)",
    phone: "8181234567",
    passes_assigned: 4,
    passes_confirmed: 4,
    rsvp_status: "confirmed",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T14:00:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: "2026-08-23T18:15:20.000Z",
    notes: "Alergias: Mariscos y nueces | Mensaje: ¡Muchísimas felicidades Sofía y Alejandro! Listos para acompañarlos en su día.",
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 2,
  },
  {
    id: "demo-guest-2",
    event_id: "demo-event-sofia-y-alejandro",
    token: "lic_roberto_garza_trevino_9021",
    name: "Lic. Roberto Garza Treviño & Esposa",
    phone: "8119876543",
    passes_assigned: 2,
    passes_confirmed: 2,
    rsvp_status: "confirmed",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T14:05:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: "2026-08-24T11:30:10.000Z",
    notes: "Alergias: Opción vegetariana para ella por favor | Mensaje: ¡Que Dios bendiga su unión y su nuevo hogar!",
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 0,
  },
  {
    id: "demo-guest-3",
    event_id: "demo-event-sofia-y-alejandro",
    token: "dr_mauricio_elizondo_pareja_7714",
    name: "Dr. Mauricio Elizondo Sada & Pareja",
    phone: "8123456789",
    passes_assigned: 2,
    passes_confirmed: 2,
    rsvp_status: "confirmed",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T14:10:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: "2026-08-24T19:40:00.000Z",
    notes: "Alergias: Sin gluten (celíaco) | Mensaje: ¡Un abrazo enorme a los dos! Ahí estaremos puntuales.",
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 0,
  },
  {
    id: "demo-guest-4",
    event_id: "demo-event-sofia-y-alejandro",
    token: "familia_cantu_villarreal_3390",
    name: "Familia Cantú Villarreal (3 pases)",
    phone: "8187654321",
    passes_assigned: 3,
    passes_confirmed: 3,
    rsvp_status: "confirmed",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T14:15:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: "2026-08-25T14:22:00.000Z",
    notes: "Alergias: Lactosa | Mensaje: Qué emoción tan grande verlos dar este paso. ¡Felicidades primos!",
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 1,
  },
  {
    id: "demo-guest-5",
    event_id: "demo-event-sofia-y-alejandro",
    token: "dra_marcela_lozano_cavazos_1156",
    name: "Dra. Marcela Lozano Cavazos & Acompañante",
    phone: null,
    passes_assigned: 2,
    passes_confirmed: 0,
    rsvp_status: "pending",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T14:20:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: null,
    notes: null,
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 0,
  },
  {
    id: "demo-guest-6",
    event_id: "demo-event-sofia-y-alejandro",
    token: "ing_daniel_ramos_sada_5521",
    name: "Ing. Daniel Ramos Sada",
    phone: null,
    passes_assigned: 1,
    passes_confirmed: 0,
    rsvp_status: "pending",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: false,
    whatsapp_sent_at: null,
    whatsapp_delivered: false,
    confirmed_at: null,
    notes: null,
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 0,
  },
  {
    id: "demo-guest-7",
    event_id: "demo-event-sofia-y-alejandro",
    token: "familia_martinez_sepulveda_6810",
    name: "Familia Martínez Sepúlveda",
    phone: "8114567890",
    passes_assigned: 4,
    passes_confirmed: 4,
    rsvp_status: "confirmed",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T14:25:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: "2026-08-26T09:15:30.000Z",
    notes: "Alergias: 1 menú infantil sin lácteos | Mensaje: Toda la familia confirmadísima, listos para festejar con todo.",
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 2,
  },
  {
    id: "demo-guest-8",
    event_id: "demo-event-sofia-y-alejandro",
    token: "valeria_tamez_flores_8842",
    name: "Valeria Tamez Flores & Pareja",
    phone: "8178901234",
    passes_assigned: 2,
    passes_confirmed: 2,
    rsvp_status: "confirmed",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T14:30:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: "2026-08-26T17:40:15.000Z",
    notes: "Mensaje: Amiga hermosa, vas a ser la novia más bonita del mundo. ¡Te quiero mucho!",
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 0,
  },
  {
    id: "demo-guest-9",
    event_id: "demo-event-sofia-y-alejandro",
    token: "lic_fernando_benavides_4102",
    name: "Lic. Fernando Benavides & Esposa",
    phone: null,
    passes_assigned: 2,
    passes_confirmed: 0,
    rsvp_status: "pending",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T14:35:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: null,
    notes: null,
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 0,
  },
  {
    id: "demo-guest-10",
    event_id: "demo-event-sofia-y-alejandro",
    token: "familia_chapa_marroquin_7231",
    name: "Familia Chapa Marroquín (5 personas)",
    phone: "8188112233",
    passes_assigned: 5,
    passes_confirmed: 5,
    rsvp_status: "confirmed",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T14:40:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: "2026-08-27T10:12:00.000Z",
    notes: "Alergias: Alergia a camarones | Mensaje: Muy honrados de acompañarlos, les deseamos toda la felicidad del mundo.",
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 2,
  },
  {
    id: "demo-guest-11",
    event_id: "demo-event-sofia-y-alejandro",
    token: "dra_patricia_sepulveda_9910",
    name: "Dra. Patricia Sepúlveda Leal",
    phone: null,
    passes_assigned: 1,
    passes_confirmed: 0,
    rsvp_status: "pending",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T14:45:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: null,
    notes: null,
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 0,
  },
  {
    id: "demo-guest-12",
    event_id: "demo-event-sofia-y-alejandro",
    token: "ing_rodrigo_morales_guerra_2209",
    name: "Ing. Rodrigo Morales Guerra & Esposa",
    phone: "8133445566",
    passes_assigned: 2,
    passes_confirmed: 2,
    rsvp_status: "confirmed",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T14:50:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: "2026-08-27T20:05:00.000Z",
    notes: "Mensaje: ¡Enhorabuena Alex y Sofi! Que el amor siga creciendo cada día más.",
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 0,
  },
  {
    id: "demo-guest-13",
    event_id: "demo-event-sofia-y-alejandro",
    token: "familia_salinas_berlanga_8103",
    name: "Familia Salinas Berlanga (3 pases)",
    phone: null,
    passes_assigned: 3,
    passes_confirmed: 0,
    rsvp_status: "pending",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T14:55:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: null,
    notes: null,
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 1,
  },
  {
    id: "demo-guest-14",
    event_id: "demo-event-sofia-y-alejandro",
    token: "claudia_alejandra_ortiz_6641",
    name: "Claudia Alejandra Ortiz & Pareja",
    phone: "8199887766",
    passes_assigned: 2,
    passes_confirmed: 2,
    rsvp_status: "confirmed",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T15:00:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: "2026-08-28T12:30:00.000Z",
    notes: "Alergias: Vegetariana para Claudia | Mensaje: ¡Qué emoción ver triunfar su amor! Nos vemos en la fiesta.",
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 0,
  },
  {
    id: "demo-guest-15",
    event_id: "demo-event-sofia-y-alejandro",
    token: "familia_garza_almaguer_5012",
    name: "Familia Garza Almaguer (4 personas)",
    phone: null,
    passes_assigned: 4,
    passes_confirmed: 0,
    rsvp_status: "pending",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T15:05:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: null,
    notes: null,
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 2,
  },
  {
    id: "demo-guest-16",
    event_id: "demo-event-sofia-y-alejandro",
    token: "dr_alberto_zambrano_3187",
    name: "Dr. Alberto Zambrano & Acompañante",
    phone: "8116789012",
    passes_assigned: 2,
    passes_confirmed: 2,
    rsvp_status: "confirmed",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T15:10:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: "2026-08-29T16:50:00.000Z",
    notes: "Mensaje: Un abrazo fraterno para ambos. Que la dicha reine siempre en su matrimonio.",
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 0,
  },
  {
    id: "demo-guest-17",
    event_id: "demo-event-sofia-y-alejandro",
    token: "familia_cavazos_montemayor_9420",
    name: "Familia Cavazos Montemayor",
    phone: null,
    passes_assigned: 3,
    passes_confirmed: 0,
    rsvp_status: "pending",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T15:15:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: null,
    notes: null,
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 1,
  },
  {
    id: "demo-guest-18",
    event_id: "demo-event-sofia-y-alejandro",
    token: "adriana_fuentes_sada_7319",
    name: "Adriana Fuentes Sada",
    phone: null,
    passes_assigned: 1,
    passes_confirmed: 0,
    rsvp_status: "pending",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: false,
    whatsapp_sent_at: null,
    whatsapp_delivered: false,
    confirmed_at: null,
    notes: null,
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 0,
  },
  {
    id: "demo-guest-19",
    event_id: "demo-event-sofia-y-alejandro",
    token: "lic_jorge_sepulveda_pareja_8201",
    name: "Lic. Jorge Sepúlveda & Pareja",
    phone: "8122334455",
    passes_assigned: 2,
    passes_confirmed: 2,
    rsvp_status: "confirmed",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T15:20:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: "2026-08-30T10:45:00.000Z",
    notes: "Alergias: Ninguna | Mensaje: ¡Felicidades hermano! Muy felices por ti y por Sofía.",
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 0,
  },
  {
    id: "demo-guest-20",
    event_id: "demo-event-sofia-y-alejandro",
    token: "familia_benitez_ramos_1640",
    name: "Familia Benítez Ramos (4 pases)",
    phone: null,
    passes_assigned: 4,
    passes_confirmed: 0,
    rsvp_status: "pending",
    table_assigned: null,
    qr_code_url: null,
    whatsapp_sent: true,
    whatsapp_sent_at: "2026-08-20T15:25:00+00:00",
    whatsapp_delivered: true,
    confirmed_at: null,
    notes: null,
    created_at: "2026-08-18T10:00:00.000Z",
    children_count: 2,
  },
]
